# fly.toml app configuration file generated for lingering-rain-7191 on 2023-06-08T16:58:02-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-rain-7191"
primary_region = "mia"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
